apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-deployment
  template:
    metadata:
      labels:
        app: django-k8s-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: registry.digitalocean.com/kt-k8s/django-k8s-web:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: django-k8s-prod-env
        env:
          - name: "PORT"
            value: "8000"    
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: kt-k8s 

---

apiVersion: v1
kind: Service
metadata:
  name: django-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: django-k8s-deployment
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8000
