name: Build Docker Container

on:
  workflow_call:
  workflow_dispatch:


jobs:
  test_django:
    uses: kkthecompguy/k8s-django-prod/.github/workflows/test-django.yaml@master
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django]
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      CLUSTER_NAME: django-k8s-cluster
    environment:
      name: testing

    steps:
      - name: pulling code
        uses: actions/checkout@v2
      - name: install doctl
        uses: digitalocean/action-doctl@v2 
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: login to DO Container registry with short-lived creds
        run: doctl registry login --expiry-seconds 1200
      - name: build container image
        working-directory: .
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/kt-k8s/django-k8s-web:latest \
            -t registry.digitalocean.com/kt-k8s/django-k8s-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: push image
        run: |
          docker push registry.digitalocean.com/kt-k8s/django-k8s-web --all-tags
      - name: k8s cluster kubeconfig file with short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: update deployment secrets
        run: |
          cat << EOF >> ./.env.prod
          DEBUG=False
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DATABASE_ENGINE=${{ secrets.DATABASE_ENGINE }}
          ALLOWED_HOST=${{ secrets.ALLOWED_HOST }}
          DB_IGNORE_SSL=${{ secrets.DB_IGNORE_SSL }}
          POSTGRES_READY=0
          POSTGRES_DB=${{ secrets.PROD_POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.PROD_POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.PROD_POSTGRES_USER }}
          POSTGRES_HOST=${{ secrets.PROD_POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.PROD_POSTGRES_PORT }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          kubectl delete secret django-k8s-prod-env
          kubectl create secret generic django-k8s-prod-env --from-env-file=./.env.prod
          
      - name: update deployment image
        run: |
          kubectl set image deployment/django-k8s-deployment  django-k8s-web=registry.digitalocean.com/kt-k8s/django-k8s-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
      - name: wait for rollout to finish
        run: |
          kubectl rollout status deployment/django-k8s-deployment
      - name: post build (migrate)
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=django-k8s-deployment -o jsonpath={.items[0].metadata.name})
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh          
    