name: "Test Django App"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test_django:
    runs-on: ubuntu-latest
    environment:
      name: testing
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      POSTGRES_PASSWORD: x1XlM-juH5LWJseJS113iQtfXL9Zf8TBBo3fXRuRh6E
      POSTGRES_DB: dockerkubes
      POSTGRES_USER: kosamtech
      DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    defaults:
      run:
        working-directory: .  

    services:
      postgres_db:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5  
  
    steps:
      - name: pulling get repo
        uses: actions/checkout@v2
      - name: install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: run test
        run: python manage.py test
